/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/yudiz1/Documents/THREEJS/THREE-REACT/crouton-jones/public/city.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/city.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="A">
          <group name="ground002" position={[54.819, 0.921, -171.252]} />
          <mesh name="Body_Taxi_old_bodycolour_0002" geometry={nodes.Body_Taxi_old_bodycolour_0002.geometry} material={materials.aaaaaa} position={[156.469, -33.066, -448.255]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.241} />
          <mesh name="defaultMaterial002" geometry={nodes.defaultMaterial002.geometry} material={materials.aaaaaa} position={[196.067, -32.917, -425.816]} rotation={[-Math.PI / 2, 0, 0]} scale={4.448} />
          <mesh name="Object_16004" geometry={nodes.Object_16004.geometry} material={materials.aaaaaa} position={[134.6, -28.791, -366.097]} scale={5.067} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.aaaaaa} position={[-12.394, -29.538, -447.418]} rotation={[-Math.PI, 0.013, -Math.PI]} scale={38.567} />
          <mesh name="Plane005_chvan_centurion_secondary_colour_0002" geometry={nodes.Plane005_chvan_centurion_secondary_colour_0002.geometry} material={materials.aaaaaa} position={[-93.804, -32.319, -448.531]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5.698, 5.698, 5.071]} />
          <mesh name="billboard002" geometry={nodes.billboard002.geometry} material={materials['bilboard.002']} position={[-198.337, 48.312, -329.512]} rotation={[Math.PI / 2, 0, 0]} scale={1.661} />
          <mesh name="billboard003" geometry={nodes.billboard003.geometry} material={materials['bilboard.001']} position={[63.457, 80.615, -125.931]} rotation={[Math.PI / 2, 0, 0.625]} scale={1.661} />
          <mesh name="billboard007" geometry={nodes.billboard007.geometry} material={materials['bilboard.002']} position={[319.638, 43.132, -368.303]} rotation={[Math.PI / 2, 0, 0]} scale={0.839} />
          <mesh name="Body_Taxi_old_bodycolour_0001" geometry={nodes.Body_Taxi_old_bodycolour_0001.geometry} material={materials.aaaaaa} position={[227.334, -33.066, -426.602]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.241} />
          <mesh name="Cube060_Material_0013" geometry={nodes.Cube060_Material_0013.geometry} material={materials['Pallet .005']} position={[282.425, 27.298, 36.149]} rotation={[0, 0.009, 0]} />
          <mesh name="Cube060_Material_0014" geometry={nodes.Cube060_Material_0014.geometry} material={materials['Pallet .005']} position={[186.586, 26.11, 101.525]} rotation={[Math.PI, -0.001, Math.PI]} />
          <mesh name="Cube060_Material_0015" geometry={nodes.Cube060_Material_0015.geometry} material={materials['Pallet .005']} position={[-222.654, 27.212, 87.8]} rotation={[0, -1.565, 0]} />
          <mesh name="Cube060_Material_0016" geometry={nodes.Cube060_Material_0016.geometry} material={materials['Pallet .005']} position={[177.016, 27.286, -141.337]} rotation={[Math.PI, -1.565, Math.PI]} />
          <mesh name="Cube060_Material_0017" geometry={nodes.Cube060_Material_0017.geometry} material={materials['Pallet .005']} position={[229.809, 27.286, -203.079]} rotation={[0, 1.565, 0]} />
          <mesh name="Cube060_Material_0018" geometry={nodes.Cube060_Material_0018.geometry} material={materials['Pallet .005']} position={[415.55, 27.212, 268.378]} rotation={[0, -1.565, 0]} />
          <mesh name="Cube198_Material003_0005" geometry={nodes.Cube198_Material003_0005.geometry} material={materials['Pallet .005']} position={[274.105, 35.49, -33.087]} rotation={[Math.PI, -0.011, Math.PI]} />
          <mesh name="Cube198_Material003_0006" geometry={nodes.Cube198_Material003_0006.geometry} material={materials['Pallet .005']} position={[433.126, 35.49, -298.016]} rotation={[Math.PI, -0.018, Math.PI]} />
          <mesh name="Cube211_Material_0003" geometry={nodes.Cube211_Material_0003.geometry} material={materials['Pallet .005']} position={[64.938, 0.944, 237.704]} rotation={[0, 1.533, 0]} />
          <mesh name="Cube288_Material_0003" geometry={nodes.Cube288_Material_0003.geometry} material={materials['Pallet .005']} position={[-172.215, 3.755, -25.919]} rotation={[0, 1.556, 0]} />
          <mesh name="Cube346_Material_0005" geometry={nodes.Cube346_Material_0005.geometry} material={materials['Pallet .005']} position={[290.183, 2.165, 86.599]} rotation={[Math.PI / 2, 0, -1.585]} scale={0.088} />
          <mesh name="Cube346_Material_0006" geometry={nodes.Cube346_Material_0006.geometry} material={materials['Pallet .005']} position={[173.85, 2.165, 184.33]} rotation={[Math.PI / 2, 0, 1.597]} scale={0.088} />
          <mesh name="Cube394_Material003_0009" geometry={nodes.Cube394_Material003_0009.geometry} material={materials['Pallet .005']} position={[-170.408, 35.684, -66.522]} />
          <mesh name="Cube394_Material003_0010" geometry={nodes.Cube394_Material003_0010.geometry} material={materials['Pallet .005']} position={[179.464, 35.678, 27.311]} rotation={[-Math.PI, 0.023, -Math.PI]} />
          <mesh name="Cube394_Material003_0011" geometry={nodes.Cube394_Material003_0011.geometry} material={materials['Pallet .005']} position={[294.747, 35.678, -174.032]} rotation={[0, -0.7, 0]} />
          <mesh name="Cube394_Material003_0012" geometry={nodes.Cube394_Material003_0012.geometry} material={materials['Pallet .005']} position={[467.796, 35.684, 114.056]} />
          <mesh name="Cube_Material_0003" geometry={nodes.Cube_Material_0003.geometry} material={materials['Pallet .005']} position={[126.838, 2.067, 239.759]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh name="ground_UrbanAtlas1_0054" geometry={nodes.ground_UrbanAtlas1_0054.geometry} material={materials.UrbanAtlas1} position={[-264.094, -34.63, -180.989]} />
          <mesh name="ground_UrbanAtlas1_0055" geometry={nodes.ground_UrbanAtlas1_0055.geometry} material={materials.UrbanAtlas1} position={[-273.045, -34.549, -491.247]} />
          <mesh name="ground_UrbanAtlas1_0056" geometry={nodes.ground_UrbanAtlas1_0056.geometry} material={materials.UrbanAtlas1} position={[-273.045, -34.549, 283.912]} />
          <mesh name="ground_UrbanAtlas1_0057" geometry={nodes.ground_UrbanAtlas1_0057.geometry} material={materials.UrbanAtlas1} position={[-273.045, -34.549, 126.708]} />
          <mesh name="ground_UrbanAtlas1_0058" geometry={nodes.ground_UrbanAtlas1_0058.geometry} material={materials.UrbanAtlas1} position={[-362.299, -34.63, -180.989]} />
          <mesh name="ground_UrbanAtlas1_0059" geometry={nodes.ground_UrbanAtlas1_0059.geometry} material={materials.UrbanAtlas1} position={[-353.348, -34.549, -491.247]} />
          <mesh name="ground_UrbanAtlas1_0060" geometry={nodes.ground_UrbanAtlas1_0060.geometry} material={materials.UrbanAtlas1} position={[-353.348, -34.549, 283.912]} />
          <mesh name="ground_UrbanAtlas1_0061" geometry={nodes.ground_UrbanAtlas1_0061.geometry} material={materials.UrbanAtlas1} position={[-353.348, -34.549, 126.708]} />
          <mesh name="ground_UrbanAtlas1_0067" geometry={nodes.ground_UrbanAtlas1_0067.geometry} material={materials.UrbanAtlas1} position={[429.03, -34.558, -181.452]} rotation={[0, 1.571, 0]} />
          <mesh name="ground_UrbanAtlas1_0068" geometry={nodes.ground_UrbanAtlas1_0068.geometry} material={materials.UrbanAtlas1} position={[397.843, -35.22, -182.71]} rotation={[0, 1.571, 0]} />
          <mesh name="ground_UrbanAtlas1_0069" geometry={nodes.ground_UrbanAtlas1_0069.geometry} material={materials.UrbanAtlas1} position={[342.122, -34.553, 273.756]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh name="ground_UrbanAtlas1_0070" geometry={nodes.ground_UrbanAtlas1_0070.geometry} material={materials.UrbanAtlas1} position={[344.209, -34.549, 115.666]} />
          <mesh name="ground_UrbanAtlas1_0071" geometry={nodes.ground_UrbanAtlas1_0071.geometry} material={materials.UrbanAtlas1} position={[344.48, -34.594, -23.663]} />
          <mesh name="ground_UrbanAtlas1_0072" geometry={nodes.ground_UrbanAtlas1_0072.geometry} material={materials.UrbanAtlas1} position={[191.523, -34.549, 423.217]} rotation={[0, 1.571, 0]} />
          <mesh name="ground_UrbanAtlas1_0073" geometry={nodes.ground_UrbanAtlas1_0073.geometry} material={materials.UrbanAtlas1} position={[34.009, -34.549, 423.217]} rotation={[0, 1.571, 0]} />
          <mesh name="ground_UrbanAtlas1_0074" geometry={nodes.ground_UrbanAtlas1_0074.geometry} material={materials.UrbanAtlas1} position={[-122.928, -34.549, 423.217]} rotation={[0, 1.571, 0]} />
          <mesh name="ground_UrbanAtlas1_0075" geometry={nodes.ground_UrbanAtlas1_0075.geometry} material={materials.UrbanAtlas1} position={[-256.306, -34.677, 423.742]} />
          <mesh name="ground_UrbanAtlas1_0076" geometry={nodes.ground_UrbanAtlas1_0076.geometry} material={materials.UrbanAtlas1} position={[-370.086, -34.677, 423.742]} />
          <mesh name="ground_UrbanAtlas1_0077" geometry={nodes.ground_UrbanAtlas1_0077.geometry} material={materials.UrbanAtlas1} position={[-201.471, -34.573, 426.421]} rotation={[0, 1.571, 0]} scale={[1, 1, 1.028]} />
          <mesh name="ground_UrbanAtlas1_0078" geometry={nodes.ground_UrbanAtlas1_0078.geometry} material={materials.UrbanAtlas1} position={[-276.283, -34.573, 354.991]} scale={[1, 1, 0.662]} />
          <mesh name="ground_UrbanAtlas1_0079" geometry={nodes.ground_UrbanAtlas1_0079.geometry} material={materials.UrbanAtlas1} position={[-356.681, -34.573, 354.757]} scale={[1, 1, 0.662]} />
          <group name="neon002" position={[-78.257, 20.256, -212.857]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.264}>
            <mesh name="Mesh029" geometry={nodes.Mesh029.geometry} material={materials.bilboard} />
            <mesh name="Mesh029_1" geometry={nodes.Mesh029_1.geometry} material={materials['Bill board emission']} />
          </group>
          <mesh name="Neon003" geometry={nodes.Neon003.geometry} material={materials.bilboard} position={[-201.567, -12.454, -211.912]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={1.264} />
          <group name="neon003" position={[-225.484, 20.271, -280.43]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.928}>
            <mesh name="Mesh044" geometry={nodes.Mesh044.geometry} material={materials['bilboard.002']} />
            <mesh name="Mesh044_1" geometry={nodes.Mesh044_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="Neon004" position={[99.691, 2.275, -483.395]} rotation={[-Math.PI, 0, 0]} scale={1.078}>
            <mesh name="Mesh060" geometry={nodes.Mesh060.geometry} material={materials['bilboard.002']} />
            <mesh name="Mesh060_1" geometry={nodes.Mesh060_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="Neon005" position={[91.094, 31.083, 146.356]} rotation={[-Math.PI, 0, 0]} scale={1.078}>
            <mesh name="Mesh062" geometry={nodes.Mesh062.geometry} material={materials.bilboard} />
            <mesh name="Mesh062_1" geometry={nodes.Mesh062_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="Neon1002" position={[-211.328, 62.292, -238.439]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.985}>
            <mesh name="Mesh027" geometry={nodes.Mesh027.geometry} material={materials.bilboard} />
            <mesh name="Mesh027_1" geometry={nodes.Mesh027_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="Neon1003" position={[30.487, 94.815, 372.179]} rotation={[Math.PI / 2, 0, 0]} scale={0.985}>
            <mesh name="Mesh055" geometry={nodes.Mesh055.geometry} material={materials.bilboard} />
            <mesh name="Mesh055_1" geometry={nodes.Mesh055_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="Object1676_UrbanAtlas3_0161" position={[110.528, -8.003, -146.976]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0165_1" geometry={nodes.Object1676_UrbanAtlas3_0165_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0165_2" geometry={nodes.Object1676_UrbanAtlas3_0165_2.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0165_3" geometry={nodes.Object1676_UrbanAtlas3_0165_3.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0165_4" geometry={nodes.Object1676_UrbanAtlas3_0165_4.geometry} material={materials.UrbanAlphaAtlas} />
            <mesh name="Object1676_UrbanAtlas3_0165_5" geometry={nodes.Object1676_UrbanAtlas3_0165_5.geometry} material={materials.UrbanAtlas5} />
          </group>
          <group name="Object1676_UrbanAtlas3_0162" position={[-172.113, 4.946, -313.673]}>
            <mesh name="Object1676_UrbanAtlas3_0166_1" geometry={nodes.Object1676_UrbanAtlas3_0166_1.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0166_2" geometry={nodes.Object1676_UrbanAtlas3_0166_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0163" position={[114.359, 0.935, -477.796]}>
            <mesh name="Object1676_UrbanAtlas3_0167_1" geometry={nodes.Object1676_UrbanAtlas3_0167_1.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0167_2" geometry={nodes.Object1676_UrbanAtlas3_0167_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0164" position={[-3.733, -1.46, -294.5]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0168" geometry={nodes.Object1676_UrbanAtlas3_0168.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0168_1" geometry={nodes.Object1676_UrbanAtlas3_0168_1.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0168_2" geometry={nodes.Object1676_UrbanAtlas3_0168_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0165" position={[-197.108, -0.112, -487.69]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0169_1" geometry={nodes.Object1676_UrbanAtlas3_0169_1.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0169_2" geometry={nodes.Object1676_UrbanAtlas3_0169_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0166" position={[-172.85, 2.066, -444.95]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0170_1" geometry={nodes.Object1676_UrbanAtlas3_0170_1.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0170_2" geometry={nodes.Object1676_UrbanAtlas3_0170_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0167" position={[-200.499, -24.033, -215.835]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.909, 1, 1]}>
            <mesh name="Object1676_UrbanAtlas3_0171_1" geometry={nodes.Object1676_UrbanAtlas3_0171_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0171_2" geometry={nodes.Object1676_UrbanAtlas3_0171_2.geometry} material={materials.UrbanAtlas1} />
          </group>
          <group name="Object1676_UrbanAtlas3_0169" position={[-174.747, -19.15, -128.873]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0173_1" geometry={nodes.Object1676_UrbanAtlas3_0173_1.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0173_2" geometry={nodes.Object1676_UrbanAtlas3_0173_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0170" position={[-241.27, -27.812, -62.317]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.838}>
            <mesh name="Object1676_UrbanAtlas3_0174_1" geometry={nodes.Object1676_UrbanAtlas3_0174_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0174_2" geometry={nodes.Object1676_UrbanAtlas3_0174_2.geometry} material={materials.UrbanAtlas1} />
          </group>
          <mesh name="Object1676_UrbanAtlas3_0171" geometry={nodes.Object1676_UrbanAtlas3_0171.geometry} material={materials.UrbanAtlas2} position={[-174.596, -3.547, -108.26]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="Object1676_UrbanAtlas3_0172" position={[-129.44, -3.029, 302.653]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0176_1" geometry={nodes.Object1676_UrbanAtlas3_0176_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0176_2" geometry={nodes.Object1676_UrbanAtlas3_0176_2.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0176_3" geometry={nodes.Object1676_UrbanAtlas3_0176_3.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0173" position={[15.379, -1.289, 35.637]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh name="Object1676_UrbanAtlas3_0177_1" geometry={nodes.Object1676_UrbanAtlas3_0177_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0177_2" geometry={nodes.Object1676_UrbanAtlas3_0177_2.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0177_3" geometry={nodes.Object1676_UrbanAtlas3_0177_3.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0174" position={[175.192, 39.693, -283.658]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0178_1" geometry={nodes.Object1676_UrbanAtlas3_0178_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0178_2" geometry={nodes.Object1676_UrbanAtlas3_0178_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0175" position={[-227.073, 39.693, -4.742]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0179_1" geometry={nodes.Object1676_UrbanAtlas3_0179_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0179_2" geometry={nodes.Object1676_UrbanAtlas3_0179_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0176" position={[-178.788, 2.214, 137.046]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0180_1" geometry={nodes.Object1676_UrbanAtlas3_0180_1.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0180_2" geometry={nodes.Object1676_UrbanAtlas3_0180_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0177" position={[268.644, -1.29, -332.098]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh name="Object1676_UrbanAtlas3_0181_1" geometry={nodes.Object1676_UrbanAtlas3_0181_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0181_2" geometry={nodes.Object1676_UrbanAtlas3_0181_2.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0181_3" geometry={nodes.Object1676_UrbanAtlas3_0181_3.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0178" position={[286.101, -4.455, 170.634]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0182_1" geometry={nodes.Object1676_UrbanAtlas3_0182_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0182_2" geometry={nodes.Object1676_UrbanAtlas3_0182_2.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0182_3" geometry={nodes.Object1676_UrbanAtlas3_0182_3.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0179" position={[26.593, 38.849, 376.767]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object1676_UrbanAtlas3_0183_1" geometry={nodes.Object1676_UrbanAtlas3_0183_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0183_2" geometry={nodes.Object1676_UrbanAtlas3_0183_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0180" position={[82.037, 29.508, 355.573]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.875}>
            <mesh name="Object1676_UrbanAtlas3_0184_1" geometry={nodes.Object1676_UrbanAtlas3_0184_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0184_2" geometry={nodes.Object1676_UrbanAtlas3_0184_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0181" position={[221.609, 3.816, 381.108]} rotation={[0, -1.571, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0185_1" geometry={nodes.Object1676_UrbanAtlas3_0185_1.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0185_2" geometry={nodes.Object1676_UrbanAtlas3_0185_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <mesh name="Object1676_UrbanAtlas3_0182" geometry={nodes.Object1676_UrbanAtlas3_0182.geometry} material={materials.UrbanAtlas3} position={[285.621, -26.802, 296.723]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0183" geometry={nodes.Object1676_UrbanAtlas3_0183.geometry} material={materials.UrbanAtlas3} position={[-124.785, -26.802, 158.613]} rotation={[-Math.PI / 2, 0, 0.662]} />
          <group name="Object1676_UrbanAtlas3_0184" position={[455.214, 4.946, -27.379]}>
            <mesh name="Object1676_UrbanAtlas3_0188_1" geometry={nodes.Object1676_UrbanAtlas3_0188_1.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0188_2" geometry={nodes.Object1676_UrbanAtlas3_0188_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0185" position={[396.934, -27.812, 118.262]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.838}>
            <mesh name="Object1676_UrbanAtlas3_0189_1" geometry={nodes.Object1676_UrbanAtlas3_0189_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0189_2" geometry={nodes.Object1676_UrbanAtlas3_0189_2.geometry} material={materials.UrbanAtlas1} />
          </group>
          <group name="Object1676_UrbanAtlas3_0186" position={[411.131, 39.693, 175.837]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0190_1" geometry={nodes.Object1676_UrbanAtlas3_0190_1.geometry} material={materials.UrbanAtlas3} />
            <mesh name="Object1676_UrbanAtlas3_0190_2" geometry={nodes.Object1676_UrbanAtlas3_0190_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <group name="Object1676_UrbanAtlas3_0187" position={[459.416, 2.214, 317.625]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0191_1" geometry={nodes.Object1676_UrbanAtlas3_0191_1.geometry} material={materials.UrbanAtlas2} />
            <mesh name="Object1676_UrbanAtlas3_0191_2" geometry={nodes.Object1676_UrbanAtlas3_0191_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <mesh name="Object1676_UrbanAtlas3_0188" geometry={nodes.Object1676_UrbanAtlas3_0188.geometry} material={materials.UrbanAtlas1} position={[-242.672, -1.274, -158.639]} rotation={[-Math.PI / 2, 0, -3.133]} />
          <mesh name="Object1676_UrbanAtlas3_0189" geometry={nodes.Object1676_UrbanAtlas3_0189.geometry} material={materials.UrbanAtlas1} position={[-256.553, -1.274, -215.96]} rotation={[-Math.PI / 2, 0, -1.561]} />
          <mesh name="Object1676_UrbanAtlas3_0190" geometry={nodes.Object1676_UrbanAtlas3_0190.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, -286.304]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0191" geometry={nodes.Object1676_UrbanAtlas3_0191.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, -384.203]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0192" geometry={nodes.Object1676_UrbanAtlas3_0192.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, -482.101]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0193" geometry={nodes.Object1676_UrbanAtlas3_0193.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, 111]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0194" geometry={nodes.Object1676_UrbanAtlas3_0194.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, 13.101]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0195" geometry={nodes.Object1676_UrbanAtlas3_0195.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, -84.797]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0196" geometry={nodes.Object1676_UrbanAtlas3_0196.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, 320.504]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0197" geometry={nodes.Object1676_UrbanAtlas3_0197.geometry} material={materials.UrbanAtlas1} position={[-247.651, -5.4, 222.606]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0198" geometry={nodes.Object1676_UrbanAtlas3_0198.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, -286.819]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0199" geometry={nodes.Object1676_UrbanAtlas3_0199.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, -384.718]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0200" geometry={nodes.Object1676_UrbanAtlas3_0200.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, -482.616]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0201" geometry={nodes.Object1676_UrbanAtlas3_0201.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, 110.484]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0202" geometry={nodes.Object1676_UrbanAtlas3_0202.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, 12.586]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0203" geometry={nodes.Object1676_UrbanAtlas3_0203.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, -85.312]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0204" geometry={nodes.Object1676_UrbanAtlas3_0204.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, 319.989]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0205" geometry={nodes.Object1676_UrbanAtlas3_0205.geometry} material={materials.UrbanAtlas1} position={[-375.933, -5.4, 222.091]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          <group name="Object1676_UrbanAtlas3_0206" position={[-313.712, -4.37, -180.837]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0210_1" geometry={nodes.Object1676_UrbanAtlas3_0210_1.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0210_2" geometry={nodes.Object1676_UrbanAtlas3_0210_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <mesh name="Object1676_UrbanAtlas3_0207" geometry={nodes.Object1676_UrbanAtlas3_0207.geometry} material={materials.UrbanAtlas1} position={[-121.805, -25.157, 112.177]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0208" geometry={nodes.Object1676_UrbanAtlas3_0208.geometry} material={materials.UrbanAtlas1} position={[-150.553, -25.157, 52.351]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0209" geometry={nodes.Object1676_UrbanAtlas3_0209.geometry} material={materials.UrbanAtlas1} position={[140.58, -1.274, 212.838]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Object1676_UrbanAtlas3_0210" geometry={nodes.Object1676_UrbanAtlas3_0210.geometry} material={materials.UrbanAtlas1} position={[151.767, -5.4, 145.238]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0211" geometry={nodes.Object1676_UrbanAtlas3_0211.geometry} material={materials.UrbanAtlas1} position={[-158.536, -5.4, 448.349]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Object1676_UrbanAtlas3_0212" geometry={nodes.Object1676_UrbanAtlas3_0212.geometry} material={materials.UrbanAtlas1} position={[-30.335, -5.4, 448.349]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Object1676_UrbanAtlas3_0213" geometry={nodes.Object1676_UrbanAtlas3_0213.geometry} material={materials.UrbanAtlas1} position={[98.797, -5.4, 448.349]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Object1676_UrbanAtlas3_0214" geometry={nodes.Object1676_UrbanAtlas3_0214.geometry} material={materials.UrbanAtlas1} position={[244.47, -5.4, 448.349]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Object1676_UrbanAtlas3_0215" geometry={nodes.Object1676_UrbanAtlas3_0215.geometry} material={materials.UrbanAtlas1} position={[370.702, -5.4, 337.987]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0216" geometry={nodes.Object1676_UrbanAtlas3_0216.geometry} material={materials.UrbanAtlas1} position={[370.702, -5.4, 226.569]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0217" geometry={nodes.Object1676_UrbanAtlas3_0217.geometry} material={materials.UrbanAtlas1} position={[370.702, -5.4, 115.151]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0218" geometry={nodes.Object1676_UrbanAtlas3_0218.geometry} material={materials.UrbanAtlas1} position={[370.702, -5.4, 0.004]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0219" geometry={nodes.Object1676_UrbanAtlas3_0219.geometry} material={materials.UrbanAtlas1} position={[310.925, -1.274, 404.36]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0220" geometry={nodes.Object1676_UrbanAtlas3_0220.geometry} material={materials.UrbanAtlas1} position={[169.441, -32.881, 250.626]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0221" geometry={nodes.Object1676_UrbanAtlas3_0221.geometry} material={materials.UrbanAtlas1} position={[191.132, -32.881, 250.302]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0222" geometry={nodes.Object1676_UrbanAtlas3_0222.geometry} material={materials.UrbanAtlas1} position={[214.765, -32.881, 250.302]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0223" geometry={nodes.Object1676_UrbanAtlas3_0223.geometry} material={materials.UrbanAtlas1} position={[239.692, -32.881, 250.302]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0224" geometry={nodes.Object1676_UrbanAtlas3_0224.geometry} material={materials.UrbanAtlas1} position={[265.591, -32.881, 250.302]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0225" geometry={nodes.Object1676_UrbanAtlas3_0225.geometry} material={materials.UrbanAtlas1} position={[177.209, -25.157, 290.877]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0226" geometry={nodes.Object1676_UrbanAtlas3_0226.geometry} material={materials.UrbanAtlas1} position={[247.897, -25.157, 290.877]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Object1676_UrbanAtlas3_0227" geometry={nodes.Object1676_UrbanAtlas3_0227.geometry} material={materials.UrbanAtlas1} position={[-242.672, -1.274, 443.801]} rotation={[-Math.PI / 2, 0, -3.133]} />
          <mesh name="Object1676_UrbanAtlas3_0228" geometry={nodes.Object1676_UrbanAtlas3_0228.geometry} material={materials.UrbanAtlas1} position={[-256.553, -1.274, 386.48]} rotation={[-Math.PI / 2, 0, -1.561]} />
          <group name="Object1676_UrbanAtlas3_0229" position={[-313.712, -4.37, 421.603]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Object1676_UrbanAtlas3_0233_1" geometry={nodes.Object1676_UrbanAtlas3_0233_1.geometry} material={materials.UrbanAtlas1} />
            <mesh name="Object1676_UrbanAtlas3_0233_2" geometry={nodes.Object1676_UrbanAtlas3_0233_2.geometry} material={materials.UrbanAlphaAtlas} />
          </group>
          <mesh name="Object1676_UrbanAtlas3_0230" geometry={nodes.Object1676_UrbanAtlas3_0230.geometry} material={materials.UrbanAtlas3} position={[-215.051, -29.657, -148.419]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0231" geometry={nodes.Object1676_UrbanAtlas3_0231.geometry} material={materials.UrbanAtlas3} position={[-207.701, -31.767, -149.399]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0232" geometry={nodes.Object1676_UrbanAtlas3_0232.geometry} material={materials.UrbanAtlas3} position={[-204.583, -31.788, -151.004]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0233" geometry={nodes.Object1676_UrbanAtlas3_0233.geometry} material={materials.UrbanAtlas3} position={[84.155, -29.657, -142.365]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0234" geometry={nodes.Object1676_UrbanAtlas3_0234.geometry} material={materials.UrbanAtlas3} position={[91.506, -31.767, -143.345]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <mesh name="Object1676_UrbanAtlas3_0235" geometry={nodes.Object1676_UrbanAtlas3_0235.geometry} material={materials.UrbanAtlas3} position={[94.624, -31.788, -144.95]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <mesh name="pCube6010" geometry={nodes.pCube6010.geometry} material={materials['bilboard.002']} position={[-232.28, 27.517, -373.9]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.936} />
          <mesh name="pCube6011" geometry={nodes.pCube6011.geometry} material={materials['bilboard.002']} position={[160.017, 96.366, -173.979]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.264} />
          <mesh name="pCube6012" geometry={nodes.pCube6012.geometry} material={materials['bilboard.002']} position={[-233.417, 49.362, -73.995]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.171} />
          <mesh name="pCube6013" geometry={nodes.pCube6013.geometry} material={materials['bilboard.001']} position={[177.942, 79.262, -281.419]} rotation={[Math.PI / 2, 0, -0.005]} scale={1.004} />
          <mesh name="pCube6014" geometry={nodes.pCube6014.geometry} material={materials['bilboard.002']} position={[188.185, 69.509, 56.563]} rotation={[Math.PI / 2, 0, 0]} scale={0.95} />
          <mesh name="pCube6015" geometry={nodes.pCube6015.geometry} material={materials['bilboard.002']} position={[210.286, 84.981, 125.8]} rotation={[Math.PI / 2, 0, 0]} scale={1.053} />
          <mesh name="pCube6016" geometry={nodes.pCube6016.geometry} material={materials['bilboard.002']} position={[157.812, 43.031, -496.014]} rotation={[Math.PI / 2, 0, 0]} scale={1.264} />
          <mesh name="pCube6017" geometry={nodes.pCube6017.geometry} material={materials['bilboard.001']} position={[203.334, 54.79, -145.411]} rotation={[Math.PI / 2, 0, 0]} scale={1.053} />
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[33.419, -35.518, -26.524]} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.aaaaaa} position={[111.321, -29.538, -210.73]} rotation={[0, 1.571, 0]} scale={38.567} />
          <mesh name="polySurface1001" geometry={nodes.polySurface1001.geometry} material={materials.bilboard} position={[-229.515, -14.642, -270.773]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.833} />
          <group name="polySurface10003" position={[-81.087, 33.265, -336.561]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.784}>
            <mesh name="Mesh047" geometry={nodes.Mesh047.geometry} material={materials['bilboard.002']} />
            <mesh name="Mesh047_1" geometry={nodes.Mesh047_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="polySurface10004" position={[-95.243, 63.862, -123.874]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh name="Mesh049" geometry={nodes.Mesh049.geometry} material={materials['bilboard.002']} />
            <mesh name="Mesh049_1" geometry={nodes.Mesh049_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="polySurface10005" position={[-47.733, 69.006, -105.295]} rotation={[1.571, 1.547, 3.142]}>
            <mesh name="Mesh056" geometry={nodes.Mesh056.geometry} material={materials['bilboard.002']} />
            <mesh name="Mesh056_1" geometry={nodes.Mesh056_1.geometry} material={materials['Bill board emission']} />
          </group>
          <mesh name="polySurface12002" geometry={nodes.polySurface12002.geometry} material={materials['bilboard.002']} position={[77.733, 41.148, -105.929]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.545} />
          <mesh name="polySurface12003" geometry={nodes.polySurface12003.geometry} material={materials['bilboard.002']} position={[-219.752, 17.556, -208.98]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.545} />
          <group name="polySurface5003" position={[-60.743, 58.383, -157.638]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.264}>
            <mesh name="Mesh038" geometry={nodes.Mesh038.geometry} material={materials.bilboard} />
            <mesh name="Mesh038_1" geometry={nodes.Mesh038_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="polySurface5004" position={[153.741, 41.258, -314.751]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={1.116}>
            <mesh name="Mesh040" geometry={nodes.Mesh040.geometry} material={materials.bilboard} />
            <mesh name="Mesh040_1" geometry={nodes.Mesh040_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="polySurface5005" position={[176.167, 17.105, 373.09]} rotation={[Math.PI / 2, 0, 0]} scale={1.116}>
            <mesh name="Mesh054" geometry={nodes.Mesh054.geometry} material={materials.bilboard} />
            <mesh name="Mesh054_1" geometry={nodes.Mesh054_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="polySurface8002" position={[94.665, 22.48, 9.005]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <mesh name="Mesh048" geometry={nodes.Mesh048.geometry} material={materials['bilboard.002']} />
            <mesh name="Mesh048_1" geometry={nodes.Mesh048_1.geometry} material={materials['Bill board emission']} />
          </group>
          <group name="polySurface8003" position={[-226.972, 56.555, -107.675]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Mesh059" geometry={nodes.Mesh059.geometry} material={materials['bilboard.002']} />
            <mesh name="Mesh059_1" geometry={nodes.Mesh059_1.geometry} material={materials['Bill board emission']} />
          </group>
          <mesh name="Roads009" geometry={nodes.Roads009.geometry} material={materials.UrbanAtlas1} position={[65.377, -34.699, -165.243]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Roads010" geometry={nodes.Roads010.geometry} material={materials.UrbanAtlas1} position={[-127.432, -34.533, 290.579]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Roads011" geometry={nodes.Roads011.geometry} material={materials.UrbanAtlas1} position={[220.755, -34.125, 301.36]} rotation={[-Math.PI / 2, 0, 0]} scale={0.813} />
          <mesh name="Roads012" geometry={nodes.Roads012.geometry} material={materials.UrbanAtlas1} position={[331.879, -34.79, 411.408]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/city.glb')
