/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import city from '../../../assets/models/city__.glb'
import { Physics, RigidBody } from '@react-three/rapier'


export function City(props) {
    const model = useGLTF(city)
    console.log("model", model.scene.children[1].children)
    return (
        <Physics debug>
            <RigidBody type="fixed" colliders="hull">
                <primitive object={model.scene} />
            </RigidBody>
        </Physics>
    )
}

useGLTF.preload(city)
