/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
export function City(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('src/assets/models/city-transformed.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="A">
                    <mesh
                        name="Body_Taxi_old_bodycolour_0002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_Taxi_old_bodycolour_0002.geometry}
                        material={materials.aaaaaa}
                        position={[156.469, -33.066, -448.255]}
                        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                        scale={0.241}
                    />
                    <mesh
                        name="defaultMaterial002"
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial002.geometry}
                        material={materials.aaaaaa}
                        position={[196.067, -32.917, -425.816]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={4.448}
                    />
                    <mesh
                        name="Object_16004"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_16004.geometry}
                        material={materials.aaaaaa}
                        position={[134.6, -28.791, -366.097]}
                        scale={5.067}
                    />
                    <mesh
                        name="Plane006"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane006.geometry}
                        material={materials.aaaaaa}
                        position={[-12.394, -29.538, -447.418]}
                        rotation={[-Math.PI, 0.013, -Math.PI]}
                        scale={38.567}
                    />
                    <mesh
                        name="Plane005_chvan_centurion_secondary_colour_0002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane005_chvan_centurion_secondary_colour_0002.geometry}
                        material={materials.aaaaaa}
                        position={[-93.804, -32.319, -448.531]}
                        rotation={[-Math.PI, 0, -Math.PI]}
                        scale={[5.698, 5.698, 5.071]}
                    />
                </group>
                <mesh
                    name="billboard002"
                    castShadow
                    receiveShadow
                    geometry={nodes.billboard002.geometry}
                    material={materials['bilboard.002']}
                    position={[-198.337, 48.312, -329.512]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={1.661}
                />
                <mesh
                    name="billboard003"
                    castShadow
                    receiveShadow
                    geometry={nodes.billboard003.geometry}
                    material={materials['bilboard.001']}
                    position={[63.457, 80.615, -125.931]}
                    rotation={[Math.PI / 2, 0, 0.625]}
                    scale={1.661}
                />
                <mesh
                    name="Body_Taxi_old_bodycolour_0001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Body_Taxi_old_bodycolour_0001.geometry}
                    material={materials.aaaaaa}
                    position={[227.334, -33.066, -426.602]}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                    scale={0.241}
                />
                <mesh
                    name="Cube060_Material_0013"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube060_Material_0013.geometry}
                    material={materials['Pallet .005']}
                    position={[282.425, 27.298, 36.149]}
                    rotation={[0, 0.009, 0]}
                />
                <mesh
                    name="ground_UrbanAtlas1_0054"
                    castShadow
                    receiveShadow
                    geometry={nodes.ground_UrbanAtlas1_0054.geometry}
                    material={materials.UrbanAtlas1}
                    position={[-264.094, -34.63, -180.989]}
                />
                <group
                    name="neon002"
                    position={[-78.257, 20.256, -212.857]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={1.264}>
                    <mesh
                        name="Mesh029"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh029.geometry}
                        material={materials.bilboard}
                    />
                    <mesh
                        name="Mesh029_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh029_1.geometry}
                        material={materials['Bill board emission']}
                    />
                </group>
                <group
                    name="Object1676_UrbanAtlas3_0161"
                    position={[110.528, -8.003, -146.976]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                        name="Object1676_UrbanAtlas3_0165"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object1676_UrbanAtlas3_0165.geometry}
                        material={materials.UrbanAtlas5}
                    />
                    <mesh
                        name="Object1676_UrbanAtlas3_0165_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object1676_UrbanAtlas3_0165_1.geometry}
                        material={materials.UrbanAtlas3}
                    />
                    <mesh
                        name="Object1676_UrbanAtlas3_0165_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object1676_UrbanAtlas3_0165_2.geometry}
                        material={materials.UrbanAlphaAtlas}
                    />
                </group>
                <mesh
                    name="Plane001"
                    // castShadow
                    receiveShadow
                    geometry={nodes.Plane001.geometry}
                    material={materials['Material.001']}
                    position={[33.419, -35.518, -26.524]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/city-transformed.glb')
