/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import city from '../../../assets/models/city__.glb'
import { Physics, RigidBody } from '@react-three/rapier'


export function City(props) {
    const model = useGLTF(city)
    const roads = model.scene.children[2].children
    const buildings = model.scene.children[1].children
    console.log("model", buildings)

    return (
        <>
            {/* Regular city model without roads */}
            <primitive object={model.scene} />

            {/* Roads with RigidBody */}
            {roads.map((road, index) => (
                <RigidBody key={index} type="fixed" colliders="hull">
                    <primitive object={road} />
                </RigidBody>
            ))}

            {/* Buildings with RigidBody */}
            {/* {buildings.map((building, index) => (
                <RigidBody key={index} type="fixed" colliders="hull">
                    <primitive object={building} />
                </RigidBody>
            ))} */}
        </>
    )
}

useGLTF.preload(city)
